### ISSUE TITLE
Documentation typo, http://projects.jga.me/routie/#toc3

### ISSUE THREAD

**Issue by mateuszjarzewski** [jgallen23/routie#41] opened 2015-09-18 15:32 UTC
http://projects.jga.me/routie/#toc3, in Advanced section, you've got:
```
routie('users/?:name', …
```
should be:
``` 
routie('users/:name?', …
```

**Comment by CtrlC-Root** [comment] 2016-01-26 05:09
@mateuszjarzewski This looks like a duplicate of #27. I'm closing this issue but feel free to continue the conversation in there.

**Closed by CtrlC-Root** 2016-01-26 05:09 UTC
Labels: documentation, duplicate
