### ISSUE TITLE
Callback/Controller function called multiple times

### ISSUE THREAD

**Issue by mateuszjarzewski** [jgallen23/routie#39] opened 2015-05-28 11:37 UTC
```JavaScript
routie('', function(){
	console.log('called')
})
routie('foobar', function(){
	return false
})
```
console:
called
called

However, this code:
```JavaScript
routie({
  '': function(){
  	console.log('called')
  },
  'foobar': function(){
  	return false
  }
})
```
console:
called

So the second sniped works fine, first one does not...

Chrome  43.0.2357.81 m
Win7 SP1 64

**Comment by mateuszjarzewski** [comment] 2015-06-03 08:09
Okay, so today I finally decide to stop using this project, because it's keep calling controller function multiple time under different circumstances that described above.... Very bad indeed.

**Comment by jalet** [comment] 2015-06-03 08:34
@mateuszjarzewski I guess you are using the library wrong. If you have a look at the source https://github.com/jgallen23/routie/blob/master/lib/routie.js#L104-L109 you can see how you are suppose to implement your routes. 

If you pass both route name and callback to ```routie(name, callback)``` routie will actually force a reload. But if you pass an object with all your routes at once, it will iterate over it, add alla handlers and then reload.

**Comment by k-vladyslav** [comment] 2015-06-09 16:27
@jalet and then we have another problem - You wont be able to decide several routes multiple times. Example
```
    routie({
                '/foo': function(){
                    console.log('foo');
                }
            });
    routie({
                '/bar': function(){
                    console.log('bar');
                }
            });
```
and If You come to page with url like http://baz.com/#/foo then in console You'll see
> foo
> foo

@jgallen23 its cool library, very light, but it lacks of public methods like "addRouter" / "removeRouter", what do You think?

**Comment by jalet** [comment] 2015-06-10 09:38
@k-vladyslav I agree with you, ```addRoute(); delRoute()``` would be nice addiotions

**Comment by CtrlC-Root** [comment] 2016-01-26 05:07
@mateuszjarzewski This issue seems to be a duplicate of #30. I'm going to close it but feel free to continue the conversation there. @jalet If you would like to see this functionality please open a separate issue or submit a pull request. Actually, pull request #24 seems similar to this, perhaps that might be of use to you.

**Closed by CtrlC-Root** 2016-01-26 05:07 UTC
Labels: discussion, duplicate
